# DEFAULT
welcome: welcome
name: name
email: email
permissions: permissions
administrator: administrator
editor: editor
collaborator: collaborator
password: password
password_confirmation: repeat password
title: title
description: description
style: style
content: content
text: text
textarea: textarea
number: number
image: image
position: position
prototype: prototype
status: status
visible: visible
invisible: invisible
settings: settings

save: save
search: search
new: new
select: select
edit: edit
delete: delete
show: show
back: back
url: url

error: Sorry, something goes wrong

# SECURITY
login_bad: Invalid username or password
logout_good: You are logged out
no_login: You must login first
permissions_error: You don't have permissions to do this action

# ADMIN
setting_updated: Site settings are updated
server_restart_required: You must restart the server
header_text: Header title
footer_text: Footer text
footer_url: Footer url
starting_guide: Starting guide
development_guide: Development guide

# Languages
languages: Languages
languages_question: How many languages do you have?
languages_answer_one: Only one language
languages_answer_two: Many languages
languages_select: Select languages

# HEADER
header_logout: Logout
header_website: Website
header_dashboard: Dashboard

# MENU
menu_home: Home
menu_users: Users
menu_pages: Pages
menu_images: Images
menu_notes: Notes
menu_configuration: Configurations

# USERS
user_singular: user
user_plural: users

user_saved: The new user is saved
user_not_saved: Sorry, the new user is not saved
user_updated: User is updated
user_not_updated: User is not updated
user_deleted: User is deleted
user_not_found: No users found
user_delete_confirmation: Do you really want to delete user?

# PAGES
page_singular: page
page_plural: pages

page_saved: The new page is saved
page_not_saved: Sorry, the new page is not saved
page_updated: Page is updated
page_not_updated: Page is not updated
page_deleted: Page is deleted
page_not_found: No pages found
page_delete_confirmation: Do you really want to delete the page?

# FIELDS
field_singular: field
field_plural: fields

field_repeater_singular: repeater
field_repeater_plural: repeaters

field_saved: The new field is saved
field_not_saved: Sorry, the new field is not saved
field_updated: Page is updated
field_not_updated: Page is not updated
field_deleted: Page is deleted
field_not_found: No fields found
field_delete_confirmation: Do you really want to delete the field?

field_type: Type of field
field_repeater_of: Repeater of

# NOTES
note_singular: note
note_plural: notes

note_saved: The new note is saved
note_not_saved: Sorry, the new note is not saved
note_updated: Note is updated
note_not_updated: Note is not updated
note_deleted: Note is deleted
note_not_found: No notes found
note_delete_confirmation: Do you really want to delete the note?

# TYPES
type_singular: object
type_plural: objects

type_saved: The new object is saved
type_not_saved: Sorry, the new object is not saved
type_updated: Object is updated
type_not_updated: Object is not updated
type_deleted: Object is deleted
type_not_found: No objects found
type_delete_confirmation: Do you really want to delete the object?

type_prototype_saved: The new object prototype is saved
type_prototype_not_saved: The new object prototype is not saved

# IMAGES
image_singular: image
image_plural: images

image_saved: The new image is saved
image_not_saved: Sorry, the new image is not saved
image_updated: Image is updated
image_not_updated: Object is not updated
image_deleted: Image is deleted
image_not_found: No images found
image_delete_confirmation: Do you really want to delete the image?

image_upload: Upload here your images
