# DEFAULT
welcome: benvenuto
name: nome
email: email
permissions: permessi
administrator: amministratore
editor: editore
collaborator: collaboratore
password: password
password_confirmation: ripeti password
title: titolo
description: descrizione
style: stile
content: contenuto
text: testo
textarea: area di testo
number: numero
image: immagine
position: posizione
prototype: prototipo
status: stato
visible: visibile
invisible: invisibile
settings: impostazioni

save: salva
search: cerca
new: nuovo
select: seleziona
edit: modifica
delete: elimina
show: visualizza
back: indietro
url: url

error: Mi spiace, qualcosa è andato storto

# SECURITY
login_bad: Email o password sbagliata
logout_good: Sei uscito correttamente
no_login: Devi prima fare il login
permissions_error: Non hai i permessi per accedere a questa funzione

# ADMIN
setting_updated: Le impostazioni del sito sono state aggiornate
server_restart_required: È necessario riavviare il server
header_text: Titolo dell'header
footer_text: Testo del footer
footer_url: Url del testo del footer
starting_guide: Guida iniziale
development_guide: Guida di sviluppo

# Languages
languages: Lingue
languages_question: Quante lingue ha il sito?
languages_answer_one: Una sola lingua
languages_answer_two: Più di una lingua
languages_select: Seleziona lingue

# HEADER
header_logout: Logout
header_website: Sito web
header_dashboard: Dashboard

# MENU
menu_home: Home
menu_users: Utenti
menu_pages: Pagine
menu_images: Immagini
menu_notes: Note
menu_configuration: Configurazione

# USERS
user_singular: utente
user_plural: utenti

user_saved: Il nuovo utente è stato creato
user_not_saved: Il nuovo utente non è stao creato
user_updated: L'utente è stato aggiornato
user_not_updated: L'utente non è stato aggiornato
user_deleted: L'utente è stato eliminato
user_not_found: Nessun utente trovato
user_delete_confirmation: Vuoi veramente eliminare l'utente?

# PAGES
page_singular: pagina
page_plural: pagine

page_saved: La nuova pagina è stata creata
page_not_saved: La nuova pagina non è stata creata
page_updated: La pagina è stata aggiornata
page_not_updated: La pagina non è stata aggiornata
page_deleted: La pagina è stata eliminata
page_not_found: Nessuna pagina trovata
page_delete_confirmation: Vuoi veramente eliminare la pagina?

# FIELDS
field_singular: campo
field_plural: campi

field_repeater_singular: ripetitore
field_repeater_plural: ripetitori

field_saved: Il nuovo campo è stato creato
field_not_saved: Il nuovo campo non è stato creato
field_updated: Il campo è stato aggiornato
field_not_updated: Il campo non è stato aggiornato
field_deleted: Il campo è  stato eliminato
field_not_found: Nessun campo trovato
field_delete_confirmation: Vuoi veramente eliminare il campo?

field_type: Tipo di campo
field_repeater_of: Ripetitore di

# NOTES
note_singular: nota
note_plural: note

note_saved: La nuova nota è stata creata
note_not_saved: La nuova nota non è stata creata
note_updated: La nota è stata aggiornata
note_not_updated: La nota non è stata aggiornata
note_deleted: La nota è stata eliminata
note_not_found: Nessuna nota trovata
note_delete_confirmation: Vuoi veramente eliminare la nota?

# TYPES
type_singular: oggetto
type_plural: oggetti

type_saved: Il nuovo oggetto è stato creato
type_not_saved: Il nuovo oggetto non è stato creato
type_updated: L'oggetto è stato aggiornato
type_not_updated: L'oggetto non è stato aggiornato
type_deleted: L'oggetto è stato eliminato
type_not_found: Nessun oggetto trovato
type_delete_confirmation: Vuoi veramente eliminare l'oggetto?

type_prototype_saved: Il nuovo prototipo di oggetto è stato creato
type_prototype_not_saved: Il nuovo prototipo di oggetto non è stato creato

# IMAGES
image_singular: immagine
image_plural: immagini

image_saved: La nuova immagine è stata creata
image_not_saved: La nuova immagine non è stata creata
image_updated: L' immagine è stata aggiornata
image_not_updated: La immagine non è stata aggiornata
image_deleted: L' immagine è stata eliminata
image_not_found: Nessuna immagine trovata
image_delete_confirmation: Vuoi veramente eliminare l' immagine?

image_upload: Carica qui le tue immagini
